services:
  general-napping_cat:
    container_name: general-napping_cat
    build: general-skills/napping-cat/src
    ports:
      - 12344:5000 # use port 5000 if you are using pwn.red 
    privileged: true  # uncomment this if you are using pwn.red 
  pwn-intro_pwntools:
    container_name: pwn-intro_pwntools
    build: pwn/intro-to-pwntools/src
    ports:
      - 10002:5000 # use port 5000 if you are using pwn.red 
    privileged: true  # uncomment this if you are using pwn.red 
  pwn-headquarters:
    container_name: pwn-headquarters
    build: pwn/headquarters/src
    ports:
      - 10003:5000 # use port 5000 if you are using pwn.red 
    privileged: true  # uncomment this if you are using pwn.red 
  pwn-headquaters_improved:
    container_name: pwn-headquarters_improved
    build: pwn/headquarters-improved/src
    ports:
      - 10004:5000 # use port 5000 if you are using pwn.red 
    privileged: true  # uncomment this if you are using pwn.red 
  web-sql:
    container_name: web-sql
    build: web/sieberrsec-query-lobby/src
    ports:
      - 10012:8000
  web-local_authority:
    container_name: web-local_authority
    build: web/local-authority/src
    ports:
      - 10010:10010 
  web-power_cookie:
    container_name: web-power_cookie
    build: web/power-cookie/src
    ports:
      - 10011:10011 
